apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: pv-jenkins
    namespace: jenkins
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/kub/volume/jenkins"